### ISSUE TITLE
Missing token prices (and hence missing TVL)

### ISSUE THREAD

**Issue by frontier159** [DefiLlama/DefiLlama-Adapters#15455]
The following tokens are missing price data on Berachain:
* KODI hOHM-HONEY: `0x2A6f7008A884563Df6FbF2d7676E696a44BB8896`
* KODI eWBERA-4-osBGT: `0x0B77545A4EB1B995e79BF85e0ed8d6Ee288ca632`
* KODI SolvBTC.BNB-xSolvBTC: `0xe21eFA586CC88271c8c87642440Ed49CCd000Ccc`

```
curl https://coins.llama.fi/prices/current/berachain:0x2A6f7008A884563Df6FbF2d7676E696a44BB8896,berachain:0x0B77545A4EB1B995e79BF85e0ed8d6Ee288ca632,berachain:0xe21eFA586CC88271c8c87642440Ed49CCd000Ccc -H 'accept: application/json'

{"coins":{}}
```

This is impacting [Origami Finance TVL](https://defillama.com/protocol/tvl/origami-finance) -- it's currently under reported by $15.5 million

What's the best way to resolve this?

**Comment by frontier159** [comment]
@noateden @waynebruce0x Would you know the best way to resolve?

Each of these are kodiak islands - ERC20 wrapping a uniV3 LP

Wrt the `KODI SolvBTC.BNB-xSolvBTC: 0xe21eFA586CC88271c8c87642440Ed49CCd000Ccc`, cross rates can get back to WBTC and hence USD. Kodiak (univ3 fork) pools:
* SolvBTC | WBTC: 0x7eB91777376b65611076Df26c36F843418fe69D2
* SolvBTC.BNB | SolvBTC: 0x2cDcdf2E38cDe5C93226450Eb096B26ED03bd6f1
* SolvBTC | xSolvBTC: 0x36815beB3494c6ad3A33540cC242d0B563fe91C0

**Comment by frontier159** [comment]
Also impacts https://defillama.com/protocol/tvl/kodiak which is under reporting by over $200 million

**Comment by waynebruce0x** [comment]
This should resolve the first: https://github.com/DefiLlama/defillama-server/pull/10169/commits/dc3d52c79881d5cf51bf47314b780ff1b55a5caa
The second is now priced
We're investigating SolvBTC.BNB before we price it, then the LP should be priced

**Comment by frontier159** [comment]
@waynebruce0x hOHM on bera is still not coming through - i have a feeling that PR has a small mistake:
https://github.com/DefiLlama/defillama-server/commit/dc3d52c79881d5cf51bf47314b780ff1b55a5caa#r162094542

Should that be:
```
  "berachain": {
    "0x5bAd2b7A0A2eEE88A4ef05d5470cdEdB0ff948EA": 
      "decimals": "18",
      "symbol": "hOHM",
      "to": "asset#ethereum:0x1db1591540d7a6062be0837ca3c808add28844f6"
    },
```

I raised a PR to update this here:
https://github.com/DefiLlama/defillama-server/pull/10174
